FROM node:latest
WORKDIR /app
COPY package.json .
COPY tsconfig.json .
COPY yarn.lock .
COPY prisma ./prisma/
COPY .env .
RUN yarn install
COPY . .
# RUN yarn global add pm2
EXPOSE 3000
# CMD ["pm2-runtime", "dist/index.js"]

# Jalanin komen di bawah cuma pertama kali (gunanya buat seeding database)
# CMD ["yarn","start:prod"]
CMD ["yarn","dev"];