FROM node:16-alpine
WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN yarn install
COPY . .
# RUN yarn build
# RUN yarn global add pm2
EXPOSE 3000
# CMD ["pm2-runtime", "dist/index.js"]
# CMD ["yarn","start:prod"];
CMD ["yarn","dev"];